spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/supply
    username: postgres
    password: mkiniz
    driverClassName: org.postgresql.Driver
    
  rabbitmq:
    addresses: localhost
    username: mkiniz
    password: foto69!!
    virtual-host: supply

